FORMAT: 1A
HOST: https://trentose2jan12-160235.herokuapp.com

# trentose2jan12-160235

Esame Ingegneria del Software 2 - 12 gennaio 2018

## Lista Astronauti [/astronauts]

### Lista di tutti gli astronauti [GET]

+ Response 200 (application/json)

        [
            {
                "firstName": "Alberto",
                "lastName": "A",
                "id": "d553defe-9efc-4aa9-9c1a-05e2ee4e523e",
                "isInSpace": true
            },
            {
                "firstName": "Federica",
                "lastName": "B",
                "id": "c380eaff-82b4-4661-a3d5-a4c122b6c766",
                "isInSpace": true
            },
            {
                "firstName": "Mario",
                "lastName": "C",
                "id": "0e801d76-f131-4a77-8da5-a963ead1e577",
                "isInSpace": false
            }
        ]

## Creazione Astronauta [/astronauts]

### Creazione di un astronauta [POST]

Per poter creare un astronauta biogna passare un form con i campi firstName, lastName e isInSpace

+ Request (application/json)

        {
            "firstName": "Nome",
            "lastName": "Cognome",
            "isInSpace": "true"
        }

+ Response 200 (application/json)

        {
            "firstName": "Nome",
            "lastName": "Cognome",
            "id": "0e801d76-f131-4a77-8da5-a963ead1e577",
            "isInSpace": true
        }
        
## Ricerca [/astronauts?lastName={lastName}]

### Ricerca astronauta per cognome [GET]

+ Parameters

    + lastName - Cognome da cercare

+ Response 200 (application/json)

        {
            "firstName": "Nome",
            "lastName": "Cognome",
            "id": "0e801d76-f131-4a77-8da5-a963ead1e577",
            "isInSpace": true
        }

## Modifica [/astronauts/{id}]

### Modifica astronauta per id [PUT]

+ Parameters

    + id - Identificativo astronauta

+ Request (application/json)

        {
            "isInSpace": "false"
        }

+ Response 200 (application/json)

        {
            "firstName": "Nome",
            "lastName": "Cognome",
            "id": "0e801d76-f131-4a77-8da5-a963ead1e577",
            "isInSpace": false
        }